addmocha implemented, test-package for symlinkewd location

diff --git a/bin/mocha b/bin/mocha
--- a/bin/mocha
+++ b/bin/mocha
@@ -1,4 +1,18 @@
-#! /bin/bash
-
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-$DIR/../mochawrapper/node_modules/.bin/mocha $@
+set -eu
+DIR="$(cd "$(dirname "$0")" && pwd)"
+MOCHA="$DIR/../mochawrapper/node_modules/mocha/bin/mocha"
+echo $MOCHA
+if [ -x "$MOCHA" ]; then
+echo "$MOCHA" "$@"
+"$MOCHA" "$@"
+else
+MOCHA="$DIR/../mocha/bin/mocha"
+echo $MOCHA
+if [ -x "$MOCHA" ]; then
+echo "$MOCHA" "$@"
+"$MOCHA" "$@"
+else
+	echo "Can't find executable"
+	exit 1
+fi
+fi
